name: Deploy Laravel to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # 3. Install dependencies (NO dev packages)
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Prepare Laravel (important!)
      - name: Laravel optimization
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 5. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C825937D3745432D8BDB531FB454EABB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B2D779D730B422CAFB0EDF36ED5202D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B606F2AB5F9C43FDAF13B713B3354D4D }}

      # 6. Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'task-manager'
          package: .
